#!/usr/bin/env bash
# Stop the 4-to_infinity_and_beyond process

# Find the PID of the script
pid=$(pgrep -f 4-to_infinity_and_beyond)

# If a PID was found, kill the process
if [ -n "$pid" ]; then
    kill "$pid"
fi
