#!/usr/bin/env bash
# Stop the 4-to_infinity_and_beyond process without using kill or killall

# Find the PID of the process
pid=$(pgrep -f 4-to_infinity_and_beyond)

# If the PID exists, terminate the process using pkill with -P
if [ -n "$pid" ]; then
    # pkill with -P sends signal to the process itself; default is SIGTERM
    pkill -P "$pid"
fi
